### ISSUE TITLE
[Editor] UI freezes when trying to the run 'store-hbase' sample without an actual HBase setup

### ISSUE THREAD

**Issue by moizalicious** [wso2/carbon-analytics#1186]
**Description:**
The UI crashes and an error is printed on the console as a constant loop when trying to run the `store-hbase` sample without an actual HBase setup.

**Affected Product Version:**
wso2sp-4.1.0-beta2-SNAPSHOT

**Steps to reproduce:**
Add the requested `.jar` files to the `{WSO2_SP_HOME}/lib` as instructed in the comment of the [store-hbase sample](https://github.com/wso2/product-sp/blob/master/modules/samples/artifacts/HBaseSample/store-hbase.siddhi), save the app and try to run.

**Comment by dnwick** [comment]
This is because backend thread does not return back , rather keep on printing connection attempts exceptions, and this happens when siddhiapp runtime start/debug. Ideally backend ajax call should be async and start button should show a progress indication trying to start the app , and should show another button to cancel it .

**Comment by dilini-muthumala** [comment]
Closing the issue as the fix is merged. This fix is avaible in hbase-store extension v4.0.11  and also will be available in Stream Processor 4.3.0 Beta release.
