### ISSUE TITLE
In Business Rules, If we give a same url for a business rule as previous one, then it will not get deployed. But in UI, it says as 'Successfully deployed the business rule'

### ISSUE THREAD

**Issue by suganyasuven** [wso2/carbon-analytics#974]
**Description:**
In Business Rules, If we give same url for a business rule as previous one, then it will not get deployed. But in UI, it says as 'Successfully deployed the business rule'. 

**Suggested Labels:**
Bug/Major

**Affected Product Version:**
wso2sp-4.0.0-beta6

**OS, DB, other environment details and versions:**    
OS: 16.04.1-Ubuntu

**Steps to reproduce:**
1) Login to the Business Rules
2) Create a Business rule using a template
3) Select Stock Exchange Template group
4) Create a business rule and click save and deploy button, it will prompt as 'successfully deployed'.
5) Create another business rule using  Stock Exchange Template group with same url.
6) Then click save and deploy button. Now also it will prompt  'successfully deployed'. 
![screenshot from 2017-12-18 16-10-16](https://user-images.githubusercontent.com/30232477/34102468-4bb8c694-e40f-11e7-9d14-7962274c3ffe.png)

But actually it will not get deployed and print the error logs in the terminal (worker).

![screenshot from 2017-12-18 16-10-43](https://user-images.githubusercontent.com/30232477/34102472-507ffc56-e40f-11e7-9257-9cdafc2b54ed.png)

7) After this error, after deleting, In UI, it will get deleted. But worker deployment folder is not updated.

**Comment by suganyasuven** [comment]
Please change the successful message saying 'Business Rule ${name} successfully deployed to worker(s)'.

**Comment by minudika** [comment]
This is because you have created two business rules with the same '**Receiver URL**'.

When deploying siddhi apps of the business rules, it will create two siddhi apps with http sources which listen to the same endpoint. Therefore one siddhi app will throw this exception since another source is already acquired that end point.
However this is occurring after siddhi app is deployed. Hence the deployment state is correct. 

@senthuran16 Let's add a note to receiver's url description in the sample mentioning this restriction?

**Comment by senthuran16** [comment]
Yes let's add in the specific field's description of the sample template, as well as making its `instanceCount` to `one`
